### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by getflourish** [oblique-bit/oblique#14] opened 2021-01-13 16:39 UTC
I’m trying to install Oblique based on the instructions in the README.

First, I naively tried to install Angular 11.0 and add Oblique as a dependency which didn’t work. I’m now aware, that this upgrade is on your roadmap.

Then, I removed `angular-cli` and installed `angular-cli@9.0.0`. I then installed a new 9.0.0 project and tried to add Oblique using `ng add @oblique/oblique`

```

npm ERR! Found: @angular/compiler@9.1.13
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~9.1.0" from the root project
npm ERR!   peer @angular/compiler@"^9.0.0 || ^10.0.0" from @oblique/oblique@5.2.1
npm ERR!   node_modules/@oblique/oblique
npm ERR!     @oblique/oblique@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"10.2.4" from @angular/localize@10.2.4
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^9.0.0 || ^10.0.0" from @oblique/oblique@5.2.1
npm ERR!   node_modules/@oblique/oblique
npm ERR!     @oblique/oblique@"*" from the root project

```

How can I resolve these issues?

I assume it’s best to wait for the upgraded version 6.0.0 of Oblique. But I would like to give it a try earlier ;)

**Comment by gillerr** [comment] 2021-01-14 10:34
Hi

I'm not sure what the problem is, but it looks like there's an angular version mismatch. Please make sure all your dependencies starting with `@angular` are on version 9 in both `package.json` and `package-lock.json`.

If this does not solve the problem, I'll need the full error log.

**Comment by getflourish** [comment] 2021-01-14 12:20
Thanks for reaching out. I cleaned everything, removed angular-cli and the project folder. Tried to install it again on version 9.0.0:

Steps to reproduce:

```npm install @angular/cli@9.0.0 -g ```
```cd path/to/my/project```
```ng new test```
=>
```✔ Packages installed successfully.
    Successfully initialized git.
```

**package.json**

```
{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.0",
    "@angular/cli": "~9.0.0",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }
}

```

```cd path/to/my/project/test```

``` ng add @oblique/oblique```

**Terminal Log**
```
An unhandled exception occurred: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.0.0
npm ERR! Found: @angular/compiler@9.0.7
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~9.0.0" from the root project
npm ERR!   peer @angular/compiler@"^9.0.0 || ^10.0.0" from @oblique/oblique@5.2.1
npm ERR!   node_modules/@oblique/oblique
npm ERR!     @oblique/oblique@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"10.2.4" from @angular/localize@10.2.4
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^9.0.0 || ^10.0.0" from @oblique/oblique@5.2.1
npm ERR!   node_modules/@oblique/oblique
npm ERR!     @oblique/oblique@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/florians/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/florians/.npm/_logs/2021-01-14T12_16_51_580Z-debug.log
Package install failed, see above.
```

**/private/var/folders/sp/vklngtbd14g6w362c1sbyjnh0000gn/T/ng-Ylgoth/angular-errors.log**

```
[error] Error: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.0.0
npm ERR! Found: @angular/compiler@9.0.7
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~9.0.0" from the root project
npm ERR!   peer @angular/compiler@"^9.0.0 || ^10.0.0" from @oblique/oblique@5.2.1
npm ERR!   node_modules/@oblique/oblique
npm ERR!     @oblique/oblique@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"10.2.4" from @angular/localize@10.2.4
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^9.0.0 || ^10.0.0" from @oblique/oblique@5.2.1
npm ERR!   node_modules/@oblique/oblique
npm ERR!     @oblique/oblique@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/florians/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/florians/.npm/_logs/2021-01-14T12_16_51_580Z-debug.log
Package install failed, see above.
    at Object.installPackage (/Users/florians/Sites/test/test/node_modules/@angular/cli/tasks/install-package.js:39:15)
    at AddCommand.run (/Users/florians/Sites/test/test/node_modules/@angular/cli/commands/add-impl.js:148:31)
    at async AddCommand.validateAndRun (/Users/florians/Sites/test/test/node_modules/@angular/cli/models/command.js:134:28)
    at async Object.runCommand (/Users/florians/Sites/test/test/node_modules/@angular/cli/models/command-runner.js:201:24)
    at async default_1 (/Users/florians/Sites/test/test/node_modules/@angular/cli/lib/cli/index.js:62:31)

``

**Comment by getflourish** [comment] 2021-01-14 12:30
Okay, after seeing the version mismatch by @angular/localize etc. tried `angular-cli@10.2.1` and then I get a different error:

```
An unhandled exception occurred: npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN tar TAR_ENTRY_ERROR ENOSPC: no space left on device, write
npm WARN tar TAR_ENTRY_ERROR ENOSPC: no space left on device, write
npm WARN tar TAR_ENTRY_ERROR ENOSPC: no space left on device, write
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/cli/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/florians/.npm/_logs/2021-01-14T12_29_11_964Z-debug.log
Package install failed, see above.
See "/private/var/folders/sp/vklngtbd14g6w362c1sbyjnh0000gn/T/ng-NCnPLM/angular-errors.log" for further details.
```

**Comment by getflourish** [comment] 2021-01-14 12:35
Going further:

```
    ** Executing migrations of package "@oblique/oblique" **
    
    ▸ Installing missing peer dependency "@angular/localize"
    ▸ Oblique: Embedding favicon
    ▸ Oblique: Embedding Master Layout
    ▸ Oblique: Adding main CSS
    ▸ Oblique: Adding theme CSS
    ▸ Oblique: Adding assets
    ▸ Oblique: Adding locale management & translations
    ▸ Oblique feature: Adding unknown route

Couldn't find a route declaration in app.module.ts.

```

**Comment by getflourish** [comment] 2021-01-14 12:45
I’ll continue to report my progress:

After adding the missing route declaration (see https://v2.angular.io/docs/ts/latest/tutorial/toh-pt5.html) I’ve now got new errors:

```
 Installing packages...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: jest@25.5.4
npm ERR! node_modules/jest
npm ERR!   dev jest@"^25.0.0" from the root project
npm ERR!   peer jest@">=24" from @angular-builders/jest@9.0.1
npm ERR!   node_modules/@angular-builders/jest
npm ERR!     dev @angular-builders/jest@"^9.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jest@"^26.0.0" from jest-preset-angular@8.3.2
npm ERR! node_modules/@angular-builders/jest/node_modules/jest-preset-angular
npm ERR!   jest-preset-angular@"^8.1.2" from @angular-builders/jest@9.0.1
npm ERR!   node_modules/@angular-builders/jest
npm ERR!     dev @angular-builders/jest@"^9.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/florians/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/florians/.npm/_logs/2021-01-14T12_44_53_797Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

```

**Comment by gillerr** [comment] 2021-01-14 14:35
It seems that Angular installs the latest `localize` version, which is not correct. It's a bug that will be solved with V6, thanks for the feedback. But you correctly solved the problem by upgrading other dependencies to V10.

Oblique cannot work without Angular's router. The error message has been improved in V6. You also correctly added it.

Now you still have a dependency mismatch: `@angular-eslint/builder` needs `@angular-devkit/build-angular" version 0.9xx.x but you have version 0.10xx.x instead. I guess this specific combination never came up before (the schematics has been written before the release of Angular 10). We'll fix that in V6. Meanwhile, can you please try embedding `@angular-eslint/builder` at version `0.1.0-beta.1`?

**Comment by getflourish** [comment] 2021-01-15 08:59
```
"@angular-eslint/builder": "0.0.1-alpha.27" => "0.1.0-beta.1"
"@angular-eslint/eslint-plugin": "0.0.1-alpha.27" => "0.1.0-beta.1"
"jest": "^25.0.0" => "^26.0.0"
"ts-node": "~8.3.0" =>  "~9.3.0"
```

**Comment by getflourish** [comment] 2021-01-15 09:34
So If I recap:

Steps for a fresh installation as of today:

1. Install `angular-cli@10.2.1`
2. Add default route configuration to `app.module.ts`
3. Upgrade a few dependencies inside `package.json`
4. Add `@oblique/oblique`

Thanks @gillerr for helping with resolving the dependency conflicts :) Looking forward to see what you’ll ship with 6.0.0 :)

**Comment by gillerr** [comment] 2021-01-15 11:42
Great ! Actually you only had a few problems to get the correct versions installed. This will be fixed with Oblique 6.

If you have some feedback on the `ng add @oblique/oblique` process, it could help me improve it. I mean did you need further steps to be able to use it in your environment? Were you happy with the default values, is something unclear, ... That sort of things.

**Comment by getflourish** [comment] 2021-01-15 13:06
Prerequisite: I’m not developing a lot with Angular. I do have a lot of experience building website and apps with Vue.js. In the past, I was working with a team on an Angular project and made a lot of comparisons to understand the differences between the two frameworks. I still prefer Vue, but I have no problem with Angular. (Obviously, I would love oblique-vue or oblique-universal 👯)

**Installation**
Overall, I think it was manageable, but without your help I would have just gave up. I’m aware that the timing is bad, because a new and more update release will arrive at some point that will be more compatible with newer versions of Angular. 😎

One thing that wasn’t obvious was how to install Oblique. That’s because the website promotes how to “update to Oblique 5” which wasn’t my use case. https://oblique.bit.admin.ch/oblique

I then went to Github. Here I found out that I should update / install Angular 9.0. 

But: How to do that? ☹️

I first installed `angular-cli` (latest). But this installed Angular 11.0+ ;)

So then I had to research first how to install an older version of Angular. Which meant: installing an older version of angular-cli first. There’s no was to install a specific Angular version through the CLI.

I then installed some 9.0 version (as advised in the README here) but with all the dependency issues, I thought maybe I should try 10.0. And I think you then followed my steps. 

**Interactive Setup**
I think it’s really cool to get all the options and learn about Oblique when installing it. From the choices I saw I noticed that you have some good ideas in there that improve on the default Angular setup. Asking about languages (i18n), fonts (…), and things like "unknown route" fallbacks are really good signs that you’re doing more than just the visual UI part. 💪

**Design**
I’m an interface designer and developer and all I can say so far is that I think Oblique looks quite solid and provides some baseline to get started. I also like that you have a Roadmap and the project looks active. I think Angular Material has some flaws, but I also think it’s a good idea to use it as a base not just for the visual UI but because it also provides some more complex interactions, form validations, etc. 

There are some minor details and some bigger things that could be improved/added, but I think it has potential to create good, standard apps for the government with it.

**Layout Composer**
I like that I could see some variations and demos upfront. I think that part could be extended to show more sample UIs built with Oblique. Just an idea for the future. I assume that you’re not really in need to showcase the framework too much to the outside and can rather use actual working applications as demo ;)

**HMR**
One thing I was missing was HMR (Hot Module Replacement), which can really help to speed up development / design. I remember working on a project that had 5–10 seconds compile time and for me as a designer this is too much time to make fast progress on a user interface when I have to wait for compilation after changing one line of CSS.

I’ve actually tried to set up HMR within this project but it wasn’t really working — because I don't need it right now (fresh project, fast compile time anyway), I also won’t spend too much effort in getting it work. Maybe it’s something worth considering? But maybe you have other real world experiences with it :) 😎

This is more or less what I’ve tried to set up HMR:
https://medium.com/@beeman/tutorial-enable-hmr-in-angular-cli-apps-1b0d13b80130

If you’re interested, here are my comparisons of my developer experience using Vue.js and Angular:

https://medium.com/@getflourish/getting-the-most-out-of-angular-hot-module-replacement-two-way-data-binding-for-custom-8ecfe702e8db

**Comment by gillerr** [comment] 2021-01-18 14:26
Thanks for your feedback.

We are working on the documentation, I know it need some improvements, for instance, the installation of Oblique within a project is not promoted enough and it could use a section to better describe the available options. It also need to clearly state which Angular version is to be used.

The Layout Composer only demonstrates the master layout possibilities but we plan to include some example pages like a search for instance.

Since Angular 11, HMR can be enabled through a simple option, as soon as Oblique has been updated, I'll have a look in it

**Closed by gillerr** 2021-01-18 14:26 UTC
