### ISSUE TITLE
oblique with OnPush change detection

### ISSUE THREAD

**Issue by bmnnnkls** [oblique-bit/oblique#95] opened 2023-03-08 11:34 UTC
while trying to improve performance of our applications i noticed that oblique's notifications stop working reliably when you change your application to on-push change detection strategy

also i realized, that oblique is triggering a huge amount of change detection cycles, probably due to binding to the mousemove event

reproduction: in obliques demo app, change AppComponent to use ChangeDetectionStrategy.OnPush, trigger a notification and then try not to move the mouse

**Comment by gillerr** [comment] 2023-03-17 14:06
Hi @bmnnnkls 

I assume that by "not working reliably", you meant the notifications are not closed automatically unless a click event occurs.

If you set the `OnPush` detection strategy on the root element, it basically forces it upon all components throughout the whole application. This means the notification component from Oblique now also uses `OnPush`. This component uses `setTimeout` to close the notifications but unfortunately, this function is outside of the detection capabilities of the `OnPush` strategy. 

This could be solved by refactoring the notification component to use `OnPush`, but this hasn't been done because nobody asked for it and it's quite a big task.  This will be discussed with the PO.

On a side note, this problem seems to be resolved with Angular 15 as I couldn't reproduce the problem with Oblique 10.


Then how do you measure the number of change detection cycles? Angular itself triggers tens of detection cycles per second, with the default change detection strategy, pretty much everything triggers one. 

In Oblique itself, there is no binding to the mousemove event. The GlobalEventService provides an Observable for the mousemove event but it's a cold one as Oblique itself doesn't subscribe to it.

**Comment by bmnnnkls** [comment] 2023-03-17 15:55
i would assume that most issues could be resolved by injecting `ChageDetectorRef` and use `detectChanges()` (or arguably `marckForCheck()`?) wherever u user this.window.setTimeout(...)

i dont remember where the mousemove subscription came from, maybe it was in our applocation.

i believe moving more and more towards OnPush change detection would lead to more performant and maintainable applications

**Comment by nina-egger** [comment] 2024-04-16 10:30
I'm closing the issue. 
OnPush change detection will not be implemented as we are aiming to use Signals.

**Closed by nina-egger** 2024-04-16 10:30 UTC
Labels: enhancement
