### ISSUE TITLE
Allow to control "Unsaved changes" / ObUnsavedChangesService globaly

### ISSUE THREAD

**Issue by WeslleyDeSouza** [oblique-bit/oblique#123] opened 2024-02-08 14:20 UTC
### Description

If the application has an auto-signoff feature due to session expiration, inactivity,  the user should be automatically redirected to the login page. However, currently, if the user is on an open form with an active "Unsaved changes" directive, the redirection is prevented until they confirm leaving. This creates a situation where the user can remain on the page even though their session is no longer valid, potentially leading to issues.

![image](https://github.com/oblique-bit/oblique/assets/20669525/b5d721bb-6830-418d-9b10-3db412a62b81)

![image](https://github.com/oblique-bit/oblique/assets/20669525/b537760e-8257-405d-aadb-e4ac33c2e32a)

### Proposed solution

```true

Not sure if this is provided in root but:

if non root instance then a global emitter to all ObUnsavedChangesService instances to disable or enable all of them at once.
If only 1 instance, then a function to disable or enable all at once.
```

We have some workaround ideas, but it would be great if "Unsaved changes" itself could offer this functionality.

Thanks alot

**Comment by nina-egger** [comment] 2024-04-02 05:23
Feature request has been accepted. Task is OUI-3010.

**Comment by nina-egger** [comment] 2024-04-02 05:25
Issue here will now be closed.

**Comment by nina-egger** [comment] 2024-04-11 10:10
I closed the wrong issue this one should be kept open. Sorry for the confusion

**Comment by swiss-design-system** [comment] 2024-04-18 11:41
We target release 11.1.0 for oui-3010

**Comment by gillerr** [comment] 2024-04-25 11:35
Hi @WeslleyDeSouza 

This is actually a duplicate of https://github.com/oblique-bit/oblique/issues/13.

You can already deactivate the feature by injecting the `ObUnsavedChangesService` and setting its `isActive` property to `false`.

**Closed by gillerr** 2024-04-25 11:35 UTC
Labels: enhancement, validated
