### ISSUE TITLE
Focus selectable doest display the glow effect

### ISSUE THREAD

**Issue by ice-blaze** [oblique-bit/oblique#133] opened 2024-07-22 10:08 UTC
### Oblique version

11.3.2

### Is this a regression?

I don't know

### Description

```true
After we programmatically focus on the selectable component, there is no glow effect around the selectable.
```

### Reproduction

```true
https://stackblitz.com/edit/oblique-master-layout-uxtymi?file=src%2Fapp%2Fhome%2Fhome.component.ts

click with the mouse on the focus button, then press one time left shift, only then you will see the glow appearing.
```

### Expected behaviour

```true
Glow should be visible after we programmatically call the `focus()` function.
```

**Comment by nina-egger** [comment] 2024-08-23 11:20
Hello @ice-blaze 

I see what you mean. I noticed we use the :focue-visible selector on the card to apply the focus styling. 

```
.ob-master-layout *:not(input,textarea,mat-select,select):focus-visible {
    box-shadow: 0 0 0 3px #8655f6;
    outline: none;
}
```

If I change it to :focus it your focus() works. Right now I don't know why we used that selector. Will talk to the team and create a ticket in our backlog.

Regards
Nina

**Comment by nina-egger** [comment] 2024-08-23 11:24
Progress tracked with ticket OUI-3274

**Comment by nina-egger** [comment] 2024-12-03 07:21
This is planned for 12.1.0

**Comment by gillerr** [comment] 2024-12-09 15:00
This has been fixed with the version 12.1.0

**Closed by gillerr** 2024-12-09 15:00 UTC
Labels: bug, validated

**Comment by ice-blaze** [comment] 2025-01-20 10:25
@gillerr it seems not to work with 12.2.3 https://stackblitz.com/edit/oblique-master-layout-r87zzrwd?file=src%2Fapp%2Fhome%2Fhome.component.ts

If the glow is on the focus button, then it works, but if the glow is on any other elements, we don't see the glow appearing on the first card.

@nina-egger I don't have the rights to reopen the issue so if you could do that it would be nice :)

**Comment by nina-egger** [comment] 2025-01-21 06:07
@ice-blaze  We created a function for this. Can you try if this works for you? https://oblique.bit.admin.ch/helpers/focus-with-outline/examples

**Comment by ice-blaze** [comment] 2025-01-21 09:58
@nina-egger I updated the exemple with the focus-with-outline function https://stackblitz.com/edit/oblique-master-layout-r87zzrwd?file=src%2Fapp%2Fhome%2Fhome.component.ts but it seems not to work either. My takes:

* Oblique [exemple](https://oblique.bit.admin.ch/helpers/focus-with-outline/examples) isn't using `obSelectable`elements it uses only `inputs`. Also I don't understand why giving an exemple with inputs if the standard `focus()` function works to have the outline.
* Why creating a function that is like a workaround, very specific to oblique, and not overriding the focus function of `ObSelectable` ? Material also have `myButton.focus()` methods, these functions should fix the outline issue IMO.
* Apparently on my personal project, the bug don't exist anymore, so it's not anymore that important for me and we could leave the bug closed. But still the stackblitz still reproduces the error ⚠️. It is maybe a configuration error or missing module.

**Comment by nina-egger** [comment] 2025-01-22 06:47
@ice-blaze 

- We should probably consider to add a card there for more diversity in elements.
- I don't remember the specifics of the feature. (why we created a function etc.). 
- On our sandbox the selectable card is focused, so I cannot reproduce it either. Really strange
