### ISSUE TITLE
Dropdown inside #obHeaderControl not working

### ISSUE THREAD

**Issue by DjolePetrovic** [oblique-bit/oblique#10] opened 2020-10-09 08:13 UTC
I tried to put in a MatMenu, MatTooltip or even the oblique dropdown control inside a #obHeaderControl. None of these components work there. The main navigation is always on top of the menu, so everything gets cut off.
Is there a workaround or even a fix for this problem?

**Comment by gillerr** [comment] 2020-10-09 22:04
If I understand your problem correctly, this is a bug that has been introduced in version 5.1.0 and fixed in 5.1.1.

Please let me know if upgrading does not solve the problem.

**Comment by DjolePetrovic** [comment] 2020-10-13 09:05
We're using 5.1.1 and it's not working.

**Comment by gillerr** [comment] 2020-11-20 12:47
Sorry for the delay, I've been quite busy lately.

I have been able to reproduce the problem with MatMenu and MatTooltip. This is a simple `z-index` problem that will be solved in the next Oblique version. Meanwhile, you can solve it with the following CSS rule:
```
.cdk-overlay-container {
    z-index: 1002;
}
```

I cannot reproduce it with the obDropdown. Is there a possibility that I can access your application so that I can understand why this doesn't work? Or can you send me the code of your `app.module.ts`, `app.component.html` and `app.component.ts` files?

Thank you

**Comment by gillerr** [comment] 2021-02-02 19:38
The `z-index` system has been completely reworked in the version 6, solving this problem.

**Closed by gillerr** 2021-02-02 19:38 UTC
Labels: bug, question
